// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag at
// 2018-12-16 16:13:40.9815424 +0800 CST m=+0.105939101

package docs

import (
	"github.com/swaggo/swag"
)

var doc = `{
    "swagger": "2.0",
    "info": {
        "description": "This is a sample server Petstore server.",
        "title": "Swagger Example API",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "1.0"
    },
    "paths": {
        "/v1/api/admin/sign_in": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "Find a count",
                "parameters": [
                    {
                        "description": "sign in information",
                        "name": "admin",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/admin.ListSignInParam"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/model.AdminSerializer"
                        }
                    }
                }
            }
        },
        "/v1/api/admin/sign_up": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "create a count",
                "parameters": [
                    {
                        "description": "sign up information",
                        "name": "admin",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/admin.ListSignUpParam"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/model.AdminSerializer"
                        }
                    }
                }
            }
        },
        "/v1/api/matches/": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Match"
                ],
                "summary": "List Match",
                "parameters": [
                    {
                        "type": "string",
                        "description": "matchID",
                        "name": "matchID",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/model.MatchSerializer"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "admin.ListSignInParam": {
            "type": "object",
            "properties": {
                "admin": {
                    "type": "object",
                    "required": [
                        "name",
                        "password"
                    ],
                    "properties": {
                        "name": {
                            "type": "string",
                            "example": "18717711819"
                        },
                        "password": {
                            "type": "string",
                            "example": "xxxxxx"
                        }
                    }
                }
            }
        },
        "admin.ListSignUpParam": {
            "type": "object",
            "properties": {
                "admin": {
                    "type": "object",
                    "required": [
                        "name",
                        "password",
                        "phone"
                    ],
                    "properties": {
                        "name": {
                            "type": "string",
                            "example": "18717711819"
                        },
                        "password": {
                            "type": "string",
                            "example": "xxxxx"
                        },
                        "phone": {
                            "type": "string",
                            "example": "18717711819"
                        }
                    }
                }
            }
        },
        "model.AdminSerializer": {
            "type": "object",
            "properties": {
                "auth_token": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "deleted_at": {
                    "type": "string"
                },
                "encrypted_password": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                },
                "state": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "model.MatchSerializer": {
            "type": "object",
            "properties": {
                "country_left": {
                    "type": "string"
                },
                "country_right": {
                    "type": "string"
                },
                "create_at": {
                    "type": "string"
                },
                "date": {
                    "type": "string"
                },
                "delete_at": {
                    "type": "string"
                },
                "group_name": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "location": {
                    "type": "string"
                },
                "match_number": {
                    "type": "integer"
                },
                "score": {
                    "type": "string"
                },
                "update_at": {
                    "type": "string"
                }
            }
        }
    }
}`

type s struct{}

func (s *s) ReadDoc() string {
	return doc
}
func init() {
	swag.Register(swag.Name, &s{})
}
